name: LuisO3BP
channels:
  - conda-forge
dependencies:
  - python=3.8
  - pip=21.0
  - setuptools=65.5.0
  - wheel>=0.38.0
  - numpy=1.21.5
  - pillow=9.2.0
  - plotly=5.9.0
  - pytest=7.1.2
  - jupyter
  - pandas             # JJ 추가
  - pytorch-cuda=11.8  # JJ 추가
  - pytorch            # JJ 추가
  - pip:
    - gym==0.21.0
    - nptyping==2.3.1
    - plotly_gif==0.0.3
    - stable-baselines3==1.8.0  # JJ 추가 : [extra] 제거하고 버전 고정
    - sb3-contrib==1.8.0        # JJ 추가